dataset:
  name: 'Cora'
  params:
      path: './data/Cora/cora'

model:
  name: 'gcn'
  params:
      hidden_channels: 16
      drop_rate: 0.5

training:
  epochs: 2000
  lr: 0.01
  alpha: 0.8 # waiting to learn, maybe it will be changed.

split:
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2

auxiliary_tasks:
  - type: 'clustering'
    params:
      n_clusters: 7
      method: 'Kmeans'
  - type: 'degree'
